export const ACTION_TYPE = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  UPDATE_GLOBAL_LOADING: 'UPDATE_GLOBAL_LOADING',
  UPDATE_OPEN_LISA_SERVER_CONNECTION_STATUS: 'UPDATE_OPEN_LISA_SERVER_CONNECTION_STATUS',
};
